/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PinSetupRouteImport } from './routes/pin-setup'
import { Route as PinLockRouteImport } from './routes/pin-lock'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersIdIndexRouteImport } from './routes/customers.$id.index'
import { Route as CustomersIdPayRouteImport } from './routes/customers.$id.pay'
import { Route as CustomersIdAddRouteImport } from './routes/customers.$id.add'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PinSetupRoute = PinSetupRouteImport.update({
  id: '/pin-setup',
  path: '/pin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PinLockRoute = PinLockRouteImport.update({
  id: '/pin-lock',
  path: '/pin-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdIndexRoute = CustomersIdIndexRouteImport.update({
  id: '/customers/$id/',
  path: '/customers/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdPayRoute = CustomersIdPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => CustomersIdRoute,
} as any)
const CustomersIdAddRoute = CustomersIdAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => CustomersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/language': typeof LanguageRoute
  '/pin-lock': typeof PinLockRoute
  '/pin-setup': typeof PinSetupRoute
  '/settings': typeof SettingsRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/customers/$id/add': typeof CustomersIdAddRoute
  '/customers/$id/pay': typeof CustomersIdPayRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/language': typeof LanguageRoute
  '/pin-lock': typeof PinLockRoute
  '/pin-setup': typeof PinSetupRoute
  '/settings': typeof SettingsRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers': typeof CustomersIndexRoute
  '/customers/$id/add': typeof CustomersIdAddRoute
  '/customers/$id/pay': typeof CustomersIdPayRoute
  '/customers/$id': typeof CustomersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/language': typeof LanguageRoute
  '/pin-lock': typeof PinLockRoute
  '/pin-setup': typeof PinSetupRoute
  '/settings': typeof SettingsRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/customers/$id/add': typeof CustomersIdAddRoute
  '/customers/$id/pay': typeof CustomersIdPayRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/language'
    | '/pin-lock'
    | '/pin-setup'
    | '/settings'
    | '/customers/new'
    | '/customers/'
    | '/customers/$id/add'
    | '/customers/$id/pay'
    | '/customers/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/language'
    | '/pin-lock'
    | '/pin-setup'
    | '/settings'
    | '/customers/new'
    | '/customers'
    | '/customers/$id/add'
    | '/customers/$id/pay'
    | '/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/language'
    | '/pin-lock'
    | '/pin-setup'
    | '/settings'
    | '/customers/new'
    | '/customers/'
    | '/customers/$id/add'
    | '/customers/$id/pay'
    | '/customers/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LanguageRoute: typeof LanguageRoute
  PinLockRoute: typeof PinLockRoute
  PinSetupRoute: typeof PinSetupRoute
  SettingsRoute: typeof SettingsRoute
  CustomersNewRoute: typeof CustomersNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  CustomersIdIndexRoute: typeof CustomersIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin-setup': {
      id: '/pin-setup'
      path: '/pin-setup'
      fullPath: '/pin-setup'
      preLoaderRoute: typeof PinSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin-lock': {
      id: '/pin-lock'
      path: '/pin-lock'
      fullPath: '/pin-lock'
      preLoaderRoute: typeof PinLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/': {
      id: '/customers/$id/'
      path: '/customers/$id'
      fullPath: '/customers/$id/'
      preLoaderRoute: typeof CustomersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/pay': {
      id: '/customers/$id/pay'
      path: '/pay'
      fullPath: '/customers/$id/pay'
      preLoaderRoute: typeof CustomersIdPayRouteImport
      parentRoute: typeof CustomersIdRoute
    }
    '/customers/$id/add': {
      id: '/customers/$id/add'
      path: '/add'
      fullPath: '/customers/$id/add'
      preLoaderRoute: typeof CustomersIdAddRouteImport
      parentRoute: typeof CustomersIdRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LanguageRoute: LanguageRoute,
  PinLockRoute: PinLockRoute,
  PinSetupRoute: PinSetupRoute,
  SettingsRoute: SettingsRoute,
  CustomersNewRoute: CustomersNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  CustomersIdIndexRoute: CustomersIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
