/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PinSetupRouteImport } from './routes/pin-setup'
import { Route as PinLockRouteImport } from './routes/pin-lock'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as FeedbackIndexRouteImport } from './routes/feedback.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CShopIdRouteImport } from './routes/c.$shopId'
import { Route as CustomersIdIndexRouteImport } from './routes/customers.$id.index'
import { Route as CShopIdIndexRouteImport } from './routes/c.$shopId.index'
import { Route as CustomersIdPayRouteImport } from './routes/customers.$id.pay'
import { Route as CustomersIdAddRouteImport } from './routes/customers.$id.add'
import { Route as CShopIdSettingsRouteImport } from './routes/c.$shopId.settings'
import { Route as CShopIdOrderRouteImport } from './routes/c.$shopId.order'
import { Route as CShopIdLoginRouteImport } from './routes/c.$shopId.login'
import { Route as CShopIdFeedbackRouteImport } from './routes/c.$shopId.feedback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PinSetupRoute = PinSetupRouteImport.update({
  id: '/pin-setup',
  path: '/pin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PinLockRoute = PinLockRouteImport.update({
  id: '/pin-lock',
  path: '/pin-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIndexRoute = FeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CShopIdRoute = CShopIdRouteImport.update({
  id: '/c/$shopId',
  path: '/c/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdIndexRoute = CustomersIdIndexRouteImport.update({
  id: '/customers/$id/',
  path: '/customers/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CShopIdIndexRoute = CShopIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CShopIdRoute,
} as any)
const CustomersIdPayRoute = CustomersIdPayRouteImport.update({
  id: '/customers/$id/pay',
  path: '/customers/$id/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdAddRoute = CustomersIdAddRouteImport.update({
  id: '/customers/$id/add',
  path: '/customers/$id/add',
  getParentRoute: () => rootRouteImport,
} as any)
const CShopIdSettingsRoute = CShopIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CShopIdRoute,
} as any)
const CShopIdOrderRoute = CShopIdOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => CShopIdRoute,
} as any)
const CShopIdLoginRoute = CShopIdLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CShopIdRoute,
} as any)
const CShopIdFeedbackRoute = CShopIdFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => CShopIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/language': typeof LanguageRoute
  '/pin-lock': typeof PinLockRoute
  '/pin-setup': typeof PinSetupRoute
  '/settings': typeof SettingsRoute
  '/c/$shopId': typeof CShopIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/c/$shopId/feedback': typeof CShopIdFeedbackRoute
  '/c/$shopId/login': typeof CShopIdLoginRoute
  '/c/$shopId/order': typeof CShopIdOrderRoute
  '/c/$shopId/settings': typeof CShopIdSettingsRoute
  '/customers/$id/add': typeof CustomersIdAddRoute
  '/customers/$id/pay': typeof CustomersIdPayRoute
  '/c/$shopId/': typeof CShopIdIndexRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/language': typeof LanguageRoute
  '/pin-lock': typeof PinLockRoute
  '/pin-setup': typeof PinSetupRoute
  '/settings': typeof SettingsRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers': typeof CustomersIndexRoute
  '/feedback': typeof FeedbackIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/c/$shopId/feedback': typeof CShopIdFeedbackRoute
  '/c/$shopId/login': typeof CShopIdLoginRoute
  '/c/$shopId/order': typeof CShopIdOrderRoute
  '/c/$shopId/settings': typeof CShopIdSettingsRoute
  '/customers/$id/add': typeof CustomersIdAddRoute
  '/customers/$id/pay': typeof CustomersIdPayRoute
  '/c/$shopId': typeof CShopIdIndexRoute
  '/customers/$id': typeof CustomersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/language': typeof LanguageRoute
  '/pin-lock': typeof PinLockRoute
  '/pin-setup': typeof PinSetupRoute
  '/settings': typeof SettingsRoute
  '/c/$shopId': typeof CShopIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/c/$shopId/feedback': typeof CShopIdFeedbackRoute
  '/c/$shopId/login': typeof CShopIdLoginRoute
  '/c/$shopId/order': typeof CShopIdOrderRoute
  '/c/$shopId/settings': typeof CShopIdSettingsRoute
  '/customers/$id/add': typeof CustomersIdAddRoute
  '/customers/$id/pay': typeof CustomersIdPayRoute
  '/c/$shopId/': typeof CShopIdIndexRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/language'
    | '/pin-lock'
    | '/pin-setup'
    | '/settings'
    | '/c/$shopId'
    | '/customers/new'
    | '/customers/'
    | '/feedback/'
    | '/orders/'
    | '/c/$shopId/feedback'
    | '/c/$shopId/login'
    | '/c/$shopId/order'
    | '/c/$shopId/settings'
    | '/customers/$id/add'
    | '/customers/$id/pay'
    | '/c/$shopId/'
    | '/customers/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/language'
    | '/pin-lock'
    | '/pin-setup'
    | '/settings'
    | '/customers/new'
    | '/customers'
    | '/feedback'
    | '/orders'
    | '/c/$shopId/feedback'
    | '/c/$shopId/login'
    | '/c/$shopId/order'
    | '/c/$shopId/settings'
    | '/customers/$id/add'
    | '/customers/$id/pay'
    | '/c/$shopId'
    | '/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/language'
    | '/pin-lock'
    | '/pin-setup'
    | '/settings'
    | '/c/$shopId'
    | '/customers/new'
    | '/customers/'
    | '/feedback/'
    | '/orders/'
    | '/c/$shopId/feedback'
    | '/c/$shopId/login'
    | '/c/$shopId/order'
    | '/c/$shopId/settings'
    | '/customers/$id/add'
    | '/customers/$id/pay'
    | '/c/$shopId/'
    | '/customers/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LanguageRoute: typeof LanguageRoute
  PinLockRoute: typeof PinLockRoute
  PinSetupRoute: typeof PinSetupRoute
  SettingsRoute: typeof SettingsRoute
  CShopIdRoute: typeof CShopIdRouteWithChildren
  CustomersNewRoute: typeof CustomersNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  FeedbackIndexRoute: typeof FeedbackIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  CustomersIdAddRoute: typeof CustomersIdAddRoute
  CustomersIdPayRoute: typeof CustomersIdPayRoute
  CustomersIdIndexRoute: typeof CustomersIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin-setup': {
      id: '/pin-setup'
      path: '/pin-setup'
      fullPath: '/pin-setup'
      preLoaderRoute: typeof PinSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin-lock': {
      id: '/pin-lock'
      path: '/pin-lock'
      fullPath: '/pin-lock'
      preLoaderRoute: typeof PinLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/': {
      id: '/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof FeedbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$shopId': {
      id: '/c/$shopId'
      path: '/c/$shopId'
      fullPath: '/c/$shopId'
      preLoaderRoute: typeof CShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/': {
      id: '/customers/$id/'
      path: '/customers/$id'
      fullPath: '/customers/$id/'
      preLoaderRoute: typeof CustomersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$shopId/': {
      id: '/c/$shopId/'
      path: '/'
      fullPath: '/c/$shopId/'
      preLoaderRoute: typeof CShopIdIndexRouteImport
      parentRoute: typeof CShopIdRoute
    }
    '/customers/$id/pay': {
      id: '/customers/$id/pay'
      path: '/customers/$id/pay'
      fullPath: '/customers/$id/pay'
      preLoaderRoute: typeof CustomersIdPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/add': {
      id: '/customers/$id/add'
      path: '/customers/$id/add'
      fullPath: '/customers/$id/add'
      preLoaderRoute: typeof CustomersIdAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$shopId/settings': {
      id: '/c/$shopId/settings'
      path: '/settings'
      fullPath: '/c/$shopId/settings'
      preLoaderRoute: typeof CShopIdSettingsRouteImport
      parentRoute: typeof CShopIdRoute
    }
    '/c/$shopId/order': {
      id: '/c/$shopId/order'
      path: '/order'
      fullPath: '/c/$shopId/order'
      preLoaderRoute: typeof CShopIdOrderRouteImport
      parentRoute: typeof CShopIdRoute
    }
    '/c/$shopId/login': {
      id: '/c/$shopId/login'
      path: '/login'
      fullPath: '/c/$shopId/login'
      preLoaderRoute: typeof CShopIdLoginRouteImport
      parentRoute: typeof CShopIdRoute
    }
    '/c/$shopId/feedback': {
      id: '/c/$shopId/feedback'
      path: '/feedback'
      fullPath: '/c/$shopId/feedback'
      preLoaderRoute: typeof CShopIdFeedbackRouteImport
      parentRoute: typeof CShopIdRoute
    }
  }
}

interface CShopIdRouteChildren {
  CShopIdFeedbackRoute: typeof CShopIdFeedbackRoute
  CShopIdLoginRoute: typeof CShopIdLoginRoute
  CShopIdOrderRoute: typeof CShopIdOrderRoute
  CShopIdSettingsRoute: typeof CShopIdSettingsRoute
  CShopIdIndexRoute: typeof CShopIdIndexRoute
}

const CShopIdRouteChildren: CShopIdRouteChildren = {
  CShopIdFeedbackRoute: CShopIdFeedbackRoute,
  CShopIdLoginRoute: CShopIdLoginRoute,
  CShopIdOrderRoute: CShopIdOrderRoute,
  CShopIdSettingsRoute: CShopIdSettingsRoute,
  CShopIdIndexRoute: CShopIdIndexRoute,
}

const CShopIdRouteWithChildren =
  CShopIdRoute._addFileChildren(CShopIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LanguageRoute: LanguageRoute,
  PinLockRoute: PinLockRoute,
  PinSetupRoute: PinSetupRoute,
  SettingsRoute: SettingsRoute,
  CShopIdRoute: CShopIdRouteWithChildren,
  CustomersNewRoute: CustomersNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  FeedbackIndexRoute: FeedbackIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  CustomersIdAddRoute: CustomersIdAddRoute,
  CustomersIdPayRoute: CustomersIdPayRoute,
  CustomersIdIndexRoute: CustomersIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
